eval "$(starship init bash)"

alias eep='systemctl suspend'
alias hibernate='systemctl hybrid-sleep'
alias restart='systemctl reboot'
alias shutdown='systemctl poweroff'
rebuild() {
    if [ -z "$1" ]
        then
            sudo nixos-rebuild switch --flake ~/dea-files#"$(hostname)"
    else
        sudo nixos-rebuild switch --flake ~/dea-files#"$1"
    fi
}
# alias rebuild='sudo nixos-rebuild switch --flake ~/dea-files'
[ -f "/home/dea/.ghcup/env" ] && . "/home/dea/.ghcup/env" # ghcup-env