# Monitors
# main monitor
# monitorrule = name:

# Startup
# exec-once waybar
# exec-once awww-daemon

exec-once = playerctld daemon

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=wlroots PATH

# Keyboard/mouse
repeat_rate = 20
repeat_delay = 200

xkb_rules_layout = us
xkb_rules_variant = basic

trackpad_natural_scrolling = 0
scroll_method = 1
disable_while_typing = 0

mouse_natural_scrolling = 0
accel_profile = 0

# https://github.com/fcitx/fcitx5 (chinese pinyin)
env=GTK_IM_MODULE,fcitx
env=QT_IM_MODULE,fcitx
env=QT_IM_MODULES,wayland;fcitx
env=SDL_IM_MODULE,fcitx
env=XMODIFIERS,@im=fcitx
env=GLFW_IM_MODULE,ibus

# Screenshare
# TODO: pipewire, pipewire-pulse, xdg-desktop-portal-wlr
#
# #source=

